### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by NickleDave** [vocalpy/sappy#1]
- [x] make `src` dir
- [x] rename `birdsonganalysis` -> `sappy`
- [x] setup.py -> pyproject.toml
- [x] use nox
- [x] move birdsonganalysis/tests into a ./tests/ directory; move data into tests/data_for_tests/
- [x] rename `notebooks` -> `docs`
- [ ] use jupytext, myst-parser et al. to convert existing notebooks into initial docs
- [ ] what's up with the global med + MAD? can this just be a constant  + a variable instead?
- [ ] represent med and MAD as dataclasses, and have constants be instances of those dataclasses?
- [ ] also let these be variables to a function, e.g. defaults for some parameter med and MAD, so that someone can pass in alternative values
- [ ] can we move the hard-coded distribution into a file instead of living in the code?
- [ ] actually write unit tests
- [ ] use Mets Brainard 2018 dataset for tests
- [ ] add Therese's version for comparison (e.g. src/therese/)
- [ ] add actual SAT code (src/SAT)
- [ ] write script that runs src/SAT on Mets Brainard to give us an oracle we can use for tests
